apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-readme-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-readme-generator
  template:
    metadata:
      labels:
        app: github-readme-generator
    spec:
      containers:
        - name: github-readme-generator
          image: sandeepavimukthi/github-readme-generator:latest
          ports:
            - containerPort: 80
