apiVersion: v1
kind: Service
metadata:
  name: readme-generator-service
  labels:
    app: readme-generator
spec:
  type: LoadBalancer
  selector:
    app: readme-generator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  sessionAffinity: None
