apiVersion: v1
kind: Service
metadata:
  name: github-readme-generator-service
spec:
  selector:
    app: github-readme-generator
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 80  # Container port
