apiVersion: v1
kind: Service
metadata:
  name: github-readme-generator-service
spec:
  selector:
    app: github-readme-generator
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # You can access your app at http://<VM_IP>:30007
